name = "reelshort-api"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
ANDROID_PACKAGE_NAME = "com.reelshort.clone"

[[d1_databases]]
binding = "DB"
database_name = "reelshort-db"
database_id = "a42dce95-e265-41d2-b81f-15ad411c9d7e"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "VIDEO_BUCKET"
bucket_name = "reelshort-videos"
